# Project-wide Gradle settings.

# JVM arguments for the daemon process
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8 -XX:+UseG1GC -Didea.java.version.compatibility.check=false

# Performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# R class optimization
android.nonTransitiveRClass=true